### ISSUE TITLE
Implement filter

### ISSUE THREAD

**Issue by kristandre** [NorwegianKiwi/codeclub-viewer#10]
Filteret skal vises på forsiden og playlist-sidene.

- Til venstre (¼ av skjermen) har vi filtrene
- Dette er i praksis checkboxes (eller knapper som holder seg inne). De er gruppert i tema ("Lag spill", "Lag app", "Roboter"), plattform ("Bare på iPad", "Ikke Windows", "Ikke Minecraft"), og fag ("Regning", "Engelsk", "Fysikk", "Lesing").
- Disse er listet opp vertikalt.
- Under hvert kurs skal det vises hvor mange oppgaver som matcher filteret
- Vi kan prøve å detektere f.eks. om man sitter på iPad, og automatisk velge dette filteret (men det må være lov å overstyre).
- Dersom man har har valgt lærermodus, så vises "fag"-filtrene øverst.
- Skjule/markere kurs som ikke har noen oppgaver som matcher filteret
- Skjule/markere oppgaver på playlist-sidene som ikke matcher filteret

**Comment by kristandre** [comment]
TODO:

- Vi kan prøve å detektere f.eks. om man sitter på iPad, og automatisk velge dette filteret (men det må være lov å overstyre)?
- Dersom man har har valgt lærermodus, så vises "fag"-filtrene øverst.
- En knapp for å resette filteret?
- Styling

**Comment by NorwegianKiwi** [comment]
@kristandre: Jeg foreslår at TODO-sakene dine legges som egne issues. You fix?

Lukker denne saken, da PR #13 er merget.
