### ISSUE TITLE
Playlist pages

### ISSUE THREAD

**Issue by kristandre** [NorwegianKiwi/codeclub-viewer#11]
- [ ] Et tydelig skille på playlists og oppgaver.
- [ ] Bytte ut "Klikk her for mer info"-teksten (som handler om et bestemt programmeringsspråk) med en tydelig lenke til "Hallo verden"-oppgaven (level 0?) som bl.a. forklarer installasjon, og har lenker til andre ressurser.
- [ ] Vise ikoner ved siden av de oppgavene som har bestemte restriksjoner (f.eks virker ikke på nettbrett, krever windows, krevert betalt konto)
- [ ] Dersom man trykker på en oppgave, så byttes hele siden ut med oppgave-siden.

**Comment by arve0** [comment]
Hvis du bruker `- [ ]` kan vi krysse de av etterhvert som de blir unnagjort :octocat:
