### ISSUE TITLE
'Start her' and 'Jeg skal undervise' buttons on front page

### ISSUE THREAD

**Issue by kristandre** [NorwegianKiwi/codeclub-viewer#12]
##### En stor grønn knapp på venstre side for de som aldri har kodet før.
- Denne skal ta deg rett til "Hei verden"-oppgaven for Scratch
- Ledetekstforslag:
  - "Lær å kode her!"
  - "Koding for nybegynnere"
  - "Jeg er nybegynner"
  - "Lær å kode"
  - "Begynn her"

##### En stor rød knapp på høyre side for den som skal undervise.
- Vil vise (uncollapse) en boks under den røde og grønne knappen med følgende innhold:
 - En tydelig forklaring om at man kan trykke på lærer/elev-toggle i menylinjen, og hva den gjør:
   - Viser lærerveiledninger på oppgavesidene.
    - Flytter filteret med skoleemner (matematikk, engelsk, norsk) øverst blant filtrene.
 - Lenker til kidsakoder.no for mer utfyllende info og veiledninger m.m (med litt tekst som sier hvilke lenker er for kodeklubber, hvilke for lærere som skal ha valgfag, etc)
- Ledetekstforslag:
 - "For lærere og veiledere"
 - “Jeg skal undervise”

**Comment by NorwegianKiwi** [comment]
Addressed by PR #14
