### ISSUE TITLE
Scratchblocks: Include all supported languages

### ISSUE THREAD

**Issue by NorwegianKiwi** [NorwegianKiwi/codeclub-viewer#144]
When Lessons.js calls `scratchblocks.renderMatching()`, it only includes languages `nb` and `en`. Instead, it should get all the supported languages for kodeklubben (it seems a little risky to only include the currently chosen language, in case a lesson is missing in that specific language, and has a fallback to a different language).

**Comment by arve0** [comment]
Many languages are not completely translated. We should pick languages that are in use. 

https://github.com/arve0/scratchblocks/tree/master/src/locales

**Comment by arve0** [comment]
#70 includes

```
var FORUM_LANGS = ['de', 'es', 'fr', 'zh_CN', 'pl', 'ja', 'nl' , 'pt', 'it',
                   'he', 'ko', 'nb', 'tr', 'el', 'ru', 'ca', 'id'];
```

You can try it out in German, for example:

    ```blocks
    Wenn die grüne Flagge angeklickt
    ```
