### ISSUE TITLE
Add support for redux-devtools-extension

### ISSUE THREAD

**Issue by NorwegianKiwi** [NorwegianKiwi/codeclub-viewer#17]
(EDIT: Changed title to show that we only want to add support for the chrome extension, and not integrate the whole thing. See https://github.com/zalmoxisus/redux-devtools-extension)

Add redux dev tools to the development build (not prod build):
https://github.com/gaearon/redux-devtools

Suggestion on how to only include in dev:
https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#exclude-devtools-from-production-builds

**Comment by kristandre** [comment]
Suggestion on how to only include in ~~prod~~ dev?

**Comment by kristandre** [comment]
Skal jeg ta med dette i #15 ?

**Comment by NorwegianKiwi** [comment]
Tja, kan du ikke se hvor uavhengig redux-devtools er? Dersom du kan lage en PR med redux-devtools som kan merges inn uavhengig av #15, så gjør det. Men dersom det er avhengig av at redux finnes allerede, så kan du enten gjøre det i samme PR, eller vente til vi har merget inn #15 og så lage en ny. Opp til deg.

**Comment by NorwegianKiwi** [comment]
Jeg foreslår at vi bare legger inn støtte for chrome-extension til redux-dev-tools:
https://github.com/zalmoxisus/redux-devtools-extension

Det er nesten ingen endringer i prosjektet, og jeg husker nå at vi hadde en issue med memory leaks og treg app i dev når vi hadde det integrert. Chrome extension fungerer dessuten bedre, for da kan man ha det som et eget debug-vindu ved siden av browseren, evt på en annen skjerm.

Se https://github.com/zalmoxisus/redux-devtools-extension for hva som må til for å aktivere støtte (vi vil ha for "universal apps").

**Comment by NorwegianKiwi** [comment]
Fixed in #26
