### ISSUE TITLE
Make webpack handle Windows separators

### ISSUE THREAD

**Issue by fredaas** [NorwegianKiwi/codeclub-viewer#22]
On Windows, when running `npm start` you end up getting 600+ error messages (one for each of the exercises in `oppgaver/src`). It seems like the path to each exercise gets stripped of its separators, consequently flooding cmd with 'Cannot resolve module' errors.

**Comment by NorwegianKiwi** [comment]
@fredaas: Jeg lukket denne, regner med det er greit nå som #41 er merget? Eller skal vi åpne den igjen?
