### ISSUE TITLE
Implement same functionality as codeclub_lesson_builder

### ISSUE THREAD

**Issue by arve0** [NorwegianKiwi/codeclub-viewer#4]
- [x] static html-pages
- [ ] scratch code blocks [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/scratch.jade#L13-L22) [2](https://github.com/arve0/codeclub_lesson_builder/blob/master/gulpfile.babel.js#L125-L126) [3](https://github.com/arve0/codeclub_lesson_builder/blob/master/package.json#L15)
- [ ] client search [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/build-search-index.js) [2](https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/search.js)
- [ ] introduction tour [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/intro.js)
- [ ] PDF [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/pdf.js)
- [ ] webhook [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/gulpfile.babel.js#L182)
- [x] playlists [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/playlists.js) [2](https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/playlist.js)
- [x] external resources [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/lesson-index.jade#L33-L34) [2](https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/index.jade#L15) [3](https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/index.js#L55-L92)
- [ ] info on hover [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/course-hover.js) [2](https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/lesson-hover.js)
- [ ] link checker [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/check-links.js)
- [x] teacher notes [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/lesson-readme.js) [2](https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/lesson-index.jade#L37-L43)

**Comment by arve0** [comment]
Might want to keep / re-use some of the existing code. [metalsmith-react-template](https://github.com/yeojz/metalsmith-react-templates) is also interesting.

**Comment by NorwegianKiwi** [comment]
static html pages: check! :)

**Comment by kristandre** [comment]
Dele denne listen i 11 forskjellige issues, slik at de kan diskuteres og lukkes hver for seg?

**Comment by arve0** [comment]
What do you want to discuss? I guess discussions about implementations can be done in PRs?

**Comment by kristandre** [comment]
Jeg tenkte egentlig på ting som ikke har direkte med implementasjonen å gjøre, som f.eks hvordan ting skal se ut, forklare ting som er uklart etc. Men siden det er snakk om å kopiere funksjonalitet du allerede har implementert, så er det kanskje ikke så mye å diskutere likevel, nei. Det hadde uansett vært kjekt å kunne bli assignet til en oppgave og gi den en 'In progress' label for å unngå at man begynner å jobbe med oppgaver andre allerede holder på med.

**Comment by NorwegianKiwi** [comment]
Hva med at de som vil gjøre en task her, legger seg selv til som "assignee", og skriver en kommentar om hva de har begynt med. Hvis det blir for uoversiktlig, kan vi jo lage egne issues, og så henvise til denne (tror en referanse-lenke skulle dukke opp her da).

**Comment by NorwegianKiwi** [comment]
Har nå delt gjenstående oppgaver i denne issue i enkeltstående issues, så lukker denne issuen.
