### ISSUE TITLE
Flytte sort av courses inn i selector

### ISSUE THREAD

**Issue by NorwegianKiwi** [NorwegianKiwi/codeclub-viewer#42]
Flytte sortering av courses ut av komponenten (CourseList) og inn i en selector. Dersom det er mulighet for at man ønsker å bruke getFilteredCourses uten at det skal sorteres, så kan man jo lage en ny selector som heter getSortedAndFilteredCourses som henter inn resultatet fra getFilteredCourses. Ellers kan man bare putte sorteringen rett inn i getFilteredCourses.

**Comment by kristandre** [comment]
getFilteredCourses returnerer et objekt. Er det mulig å sortere objekter sine properties?

**Comment by NorwegianKiwi** [comment]
Hm, nei, det er sant. Hva om man lager en ekstra selector som henter inn getFilteredCourses som en av parameterene, og spytter ut den sorterte arrayen av keys? Det burde ikke koste noe mer, siden getFilteredCourses er memoized (for å dobbelsjekke kunne man legge inn en console.log eller noe og se at den bare blir kjørt 1 gang).

**Comment by kristandre** [comment]
Hvis vi lager en selector som returnerer en array av sorterte keys, så må vi få både `filteredCourses` og `sortedCourseKeys` som props. Deretter må man sjekke om filteredCourses har alle keys (?), og så mappe disse til `courses`.  Det virker som litt mye styr å flytte sortering til en egen selector hvis man allikevel må mappe keys til `courses` etterpå, spesielt med tanke på at det foreløpig kun er CourseList som trenger å sortere kursene basert på antall oppgaver de har.

**Comment by NorwegianKiwi** [comment]
Bare at den blir memoized. Men enig at det er mye styr med den foreslåtte løsningen... Det er vel uansett en ganske kort liste å sortere, så det er vel ikke noe problem. Dersom siden begynner å gå sakte, får vi åpne en ny issue.
