### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by arve0** [NorwegianKiwi/codeclub-viewer#45]
Also see links to existing code in #4.

**Scratchblocks**:
Seems like one needs `parse` and `render` in scrachblocks: https://github.com/tjvr/scratchblocks/blob/master/src/scratchblocks.js#L2588-L2589

**Other languages**:
Use highlight.js: https://highlightjs.org

**Comment by arve0** [comment]
markdown-it has a highlight option: https://github.com/markdown-it/markdown-it/blob/master/README.md#init-with-presets-and-options

**Comment by arve0** [comment]
> @NorwegianKiwi:  kunne du forklart hvordan scratchblocks highlighting fungerer med codeclub_lesson_builder?

Scratchblocks er [lagt til i vendor script](https://github.com/arve0/codeclub_lesson_builder/blob/master/gulpfile.babel.js#L125-L126). Scratch-oppgaver bruker sin [egen layout](https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/scratch.jade#L13-L22) som kjører scratchblocks på kodeblokker og inline kode. Scratchblocks gjør dette:

1. Henter teksten i kodeblokken
2. Lager et "doc" av kodeteksten <-- dette er `parse` nevnt over
3. Konverterer "doc" til SVG  <-- dette er `render` nevnt over
4. Bytter ut kodeblokken med SVG

Legg merke til at jeg har laget [et eget bygg av scratchblocks](https://github.com/arve0/codeclub_lesson_builder/blob/master/package.json#L15) som bare inneholder norsk.

> (Og gjerne highlight.js også, skjønte ikke helt hvordan det var gjort...)

highlight.js er parser tekst fra kodeblokker med markdown-it's egen option `highlight`: https://github.com/arve0/codeclub_lesson_builder/blob/master/markdown.js#L13

**Comment by arve0** [comment]
Highlighting is already [included in markdown-it-loader](https://github.com/unindented/markdown-it-loader/blob/master/index.js#L21-33), but we are missing the styles.

![skjermbilde 2016-07-06 kl 00 56 55](https://cloud.githubusercontent.com/assets/4810521/16602461/94d80b84-4314-11e6-8247-23450f372112.png)

**Comment by NorwegianKiwi** [comment]
I see that scratchblocks uses jquery to alter the Dom. But the also exists a react-scratchblocks, perhaps we could use that?

**Comment by NorwegianKiwi** [comment]
Ah, so perhaps just add highlight styles locally to Lesson.js?

**Comment by arve0** [comment]
> I see that scratchblocks uses jquery to alter the Dom. But the also exists a react-scratchblocks, perhaps we could use that?

I would rather use markdown-it highlight option along with `parse` and `render` (`lang === 'blocks'`). Then  all highlighting are in the same place.

**Comment by arve0** [comment]
> Ah, so perhaps just add highlight styles locally to Lesson.js?

Isn't styles explicit? Or can one do

```
import './path/to/idea.css'
```

to have "global" styles?

**Comment by NorwegianKiwi** [comment]
There are 3 scopes of css. If you run `npm run build` to build the static files (and `npm run serve`) you will notice the following:

Any css that is extracted using extract-text-webpack-plugin (currently only the bootstrap-css, but this also includes stuff that bootstrap includes via app.scss) is "real, global css", and is put in vendor2.css (for bootstrap) and vendor.css (for everything else, which is currently nothing). This will have the lowest specificity, but is included once via a link-tag in the html. The css we put here should be stuff that is applicable to many different pages (and with "pages" I mean react-pages or classes, not different renderings of one page like Lesson.js).

Then there is the "local" css provided by css-modules, and is included with
```
import mystyle from '...../mystyles.scss'; // var mystyle = require('...../mystyles.scss');
...
<div className={mystyle.aCssClass}> ... </div>
```
where `aCssClass` is a css class-definition in `mystyles.scss`. Here, css-modules will garble the name of the class to make it globally unique (using `localIdentName=[name]__[local]__[hash:base64:5]` found in `webpack.base.config.babel.js`) and inject the css into a `<style>`-tag in the head whenever you visit that page. It is "global", but because of the garbling, it behaves as if it was local. Also, since it is in a `<style>` tag it will have higher precedence than the css in vendor2.css. Note that for the static html-files, the style is already there (in case you go to that page directly, since we don't want FOUC).

Finally there is inline css, i.e.
```html
<div style={{backgroundColor: 'white'}}>....</div>
```
This is style that stays in the tag. This has the highest specificity, but you cannot have pseudo-elements. We almost never use this.

**Comment by NorwegianKiwi** [comment]
Now, if there is css that only Lesson.js uses, we could perhaps make it work by changing the html we get from createMarkup() in Lesson.js before inserting it into the page. Not sure if that would work though. When it comes to idea.css from highlight.js it might be just as well to have it included globally by app.scss. But it is a question whether all the css for the lesson html must be global, or if we can (or want to) fit it in somehow using loaders. If the same css is used in almost all the lessons, we probably want it global, or else it will have to be reloaded for every page.

For the svg, an idea could be to have a webpack-loader process the html (f.eks. by adding another loader in front of 'html' in `contentLoaders` in `webpack.base.config.babel.js`, og perhaps the html-loader takes some attributes?) and have it spit out the "correct" html before it is given to `Lesson.js`.

Now, all the css for borders etc, where can we find that in the codeclub_lesson_builder?

**Comment by arve0** [comment]
> we could perhaps make it work by changing the html we get from createMarkup() in Lesson.js before inserting it into the page.

That will be almost like DOM-manipulation, doesn't feel right, does it?

>  If the same css is used in almost all the lessons

It will be used in all common languages. Python, JS, Lua, Processing, etc.

> For the svg, an idea could be to have a webpack-loader process the html (f.eks. by adding another loader in front of 'html' in contentLoaders in webpack.base.config.babel.js, og perhaps the html-loader takes some attributes?) and have it spit out the "correct" html before it is given to Lesson.js.

Why use another route for scratch code than other languages? SVG is text, so it's fundamentally equal to the `<spans>` from highlight.js.

Give me a day or two, and I'll update #70.

**Comment by arve0** [comment]
After hacking a bit in scratchblocks, it seems like there is no way to make it work without a browser, as it depends on rendering in DOM to get size of elements. Which means possible solutions are:

- rewrite SVG-renderer in scratchblocks (I have no idea how to do this)
- use client side DOM-manipulation

**Comment by NorwegianKiwi** [comment]
Are you sure we need a browser? As you can see in index-static.js, we render to html using ReactDOMServer.renderToString (see https://facebook.github.io/react/docs/top-level-api.html#reactdomserver), or we could use ReactDOMServer.renderToStaticMarkup. As long as we have a react-component to render.

If I understand scratchblocks correctly, it changes the DOM on the client. But if possible, I think it would be better if we could change the html during compile, and probably do so using the webpack-loaders (which process the markdown). That would mean that the lesson.content would already contain the svgs.

**Comment by arve0** [comment]
> Are you sure we need a browser?

Pretty sure. One can rewrite the scratchblocks SVG renderer as mentioned, but I do not have the time for putting in that effort right now.

> If I understand scratchblocks correctly, it changes the DOM on the client.

That is correct, but not the essential part. The essential part is that the scratchblocks SVG render uses the DOM for measuring the length of the visual elements. I assume it is the text that can vary in size, but have not checked. The part I'm talking about now is the commented out part in `Label.measureAll` in the [linked commit from above](https://github.com/arve0/scratchblocks/commit/4b0fa0de6e49a3b14e76f767dc218873bedae4c5).

> But if possible, I think it would be better if we could change the html during compile, and probably do so using the webpack-loaders (which process the markdown). That would mean that the lesson.content would already contain the svgs.

Totally agree, but I do not see an easy fix for this. I'll open an issue on scratchblocks now and ask if they have thought of a pure renderer without DOM.

**Comment by NorwegianKiwi** [comment]
See PR #143 and issue #144 and issue #145.

**Comment by NorwegianKiwi** [comment]
(Old PR #70 and PR #140 also have some relevant comments)

**Comment by NorwegianKiwi** [comment]
Here are some links to codeclub_lesson_builder, copied from a different issue that I am about to close: [1](https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/scratch.jade#L13-L22) [2](https://github.com/arve0/codeclub_lesson_builder/blob/master/gulpfile.babel.js#L125-L126) [3](https://github.com/arve0/codeclub_lesson_builder/blob/master/package.json#L15)

**Comment by NorwegianKiwi** [comment]
@arve0, is there anything left in this issue, or can we close? Is all code now highlighted in master?

**Comment by arve0** [comment]
I think that should be all.
