### ISSUE TITLE
font-awesome.min.css blir lastet hver gang man går til PlaylistPage

### ISSUE THREAD

**Issue by NorwegianKiwi** [NorwegianKiwi/codeclub-viewer#62]
Hver gang man går til PlaylistPage, så blir følgende to url'er kalt (de blir altså ikke cachet av browser):
```
https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css
https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/fonts/fontawesome-webfont.woff2?v=4.6.3
```
Sånn bør det ikke være. Enten bør fontene lastes ned så de ligger lokalt hos oss, eller så må vi sørge for at browser cacher dem.

**Comment by kristandre** [comment]
Fra `components/LessonList/LessonItem.scss/`

> 
```
//TODO: Replace Font Awesome with custom icons?
@import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css');
```

Altså blir FA brukt til å vise midlertidige ikoner i oppgavelisten. Hvis vi har tenkt å bruke FA andre steder, så kan vi kanskje bruke [react-fontawesome](https://www.npmjs.com/package/react-fontawesome)?

**Comment by arve0** [comment]
Hvis det kun er noen få ikoner som trengs, vil kanskje PNG være lettere? [icons8](https://icons8.com) kan være et alternativ. Jeg har lisens på [glyphicons](http://glyphicons.com), som også kommer som bildefiler.
