### ISSUE TITLE
Eksterne kurs

### ISSUE THREAD

**Issue by kristandre** [NorwegianKiwi/codeclub-viewer#86]
Hvordan skal eksterne kurs vises på forsiden? I samme liste som vanlige kurs? En egen liste?

Skal eksterne kurs ha egne tags slik at de kan filtreres på samme måte som vanlige kurs og oppgaver? Hvis JA, skal alle kurs ha egne tags, i tillegg til tags som finnes i oppgavene?

**Comment by arve0** [comment]
> Hvordan skal eksterne kurs vises på forsiden? I samme liste som vanlige kurs? En egen liste?

Jeg synes de skal vises i lag med vanlige kurs, men at det er tydelig at oppgaven er ekstern. Ettersom vi ikke lett kan finne ut hvor mange oppgaver som er i kurset, sorteres de i bunn (sortert etter antall oppgaver).

> Skal eksterne kurs ha egne tags slik at de kan filtreres på samme måte som vanlige kurs og oppgaver? 

Hva mener du med "egne tags"? Altså tags, slik som alle andre kurs? I så tilfelle, så ja, hvorfor ikke?

**Comment by NorwegianKiwi** [comment]
Spennende idé, at tags fra course gjelder for alle lessons. Et problem er da er at en lesson kan ikke "ta vekk" tags fra course, dersom et bestemt kurs skulle ønske å overskrive dette.

Akkurat nå virker det mer fornuftig å bare tillate tags på eksterne kurs. Da vil jo eksterne kurs oppføre seg ganske forskjellig fra "vanlige" kurs, men det gjør kanskje ikke noe, for de er jo nokså forskjellige uansett?

Finnes det kurs der noen av lessons er eksterne (og andre interne)? Men da klarer vi vel å lage tags på de eksterne lessons uansett, så dette vil vel ikke være noe problem?

**Comment by kristandre** [comment]
Akkurat nå virker å kun tillate tags på eksterne kurs som den enkleste løsningen (slipper å endre så mye på gjeldende struktur). 

Det finnes kurs med både interne og eksterne lessons. Se f.eks 'Videokurs' oppgavesamlingen på scratch. Disse oppgavene kan bli tagget og oppfører seg som vanlige lessons, den eneste forskjellen er at de linker til en ekstern side i stedet for en subside.

**Comment by NorwegianKiwi** [comment]
Da synes jeg vi skal går for det. Om vi har lyst å utvide senere til å tagge vanlige kurs, får vi tenke gjennom det da.
